<<<<<<< HEAD
# Site settings
title: Misia VR
email:
description: A jekyll template for landing pages, portfolio and blogging

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://jekynewage.github.io" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 2973388149
data-ad-client: ca-pub-9204963049240271
google_ad_client: ca-pub-9204963049240271

google_analytics: "UA-86331249-1"
addthis_id: ra-5644da281510c62f
disqus_account: jeky-new-age

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/lantoniotrento
  - title: facebook
    url: https://facebook.com/lantoniotrento
  - title: google-plus
    url: https://plus.google.com/+AntoniotrentoIt
  #- title: github
  #  url: http://github.com/jekyll

# Build settings
markdown: kramdown
highlighter: blue
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
=======
# Site
name: 'TEST'
description: 'Mundana is a free Jekyll theme for awesome people like you, Medium like.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'monika.zatylny@gmail.com'
mailchimp-list: 

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    monika:
      name:           Monika
      site:           misinhap
      avatar:         /assets/images/avatar1.jpg
      bio:            "Hi"
      email:          monika.zatylny@gmail.com
      twitter:        

    jane:
      name:           Jane
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Monika
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
>>>>>>> 85787b7da00e1a1508e8bccdc7477462f7fbca74
